# NumPy : Introduction

**NumPy allows you to manipulate data in the form of an array.**

**Complete the missions below using NumPy.**

In [ ]:

import numpy as np # Here we rename numpy as np, it's shorter, and everybody does that

# Mission 1 : Display the version of NumPy you are running (as each library, you can use np.__version__)
np.__version__

'1.23.5'

In [ ]:
# Mission 2 : Create a NumPy array with a length of 3, that contains this 3 floats: 0.8, 0.6, 0.4
# Expected result: array([0.8, 0.6, 0.4])
np.array([0.8, 0.6, 0.4])

array([0.8, 0.6, 0.4])

In [ ]:
# Mission 3 : Create a function that uses the np.random.random() function to return an array with 10 random elements,
# all of which must be greater than 0.25 and less than 1.0

# Example of expected result: array([0.3897948 , 0.82850041, 0.5499838 , 0.81940137, 0.92175875, 0.89634373, 0.26821861, 0.72376496, 0.81098623, 0.28192741])

np.random.random(10) * 0.75 + 0.25

array([0.40725887, 0.79979015, 0.65634883, 0.85309126, 0.25737873,
       0.91165066, 0.36214421, 0.93683953, 0.94786423, 0.97690759])

In [ ]:
# Mission 4 : What does the np.empty() method do? Don't just copy the documentation, explain in your own words here
np.empty((5, 3))

# it creates an array of shape passed in a tuple and fills it with values already allocated in interpreter memory

array([[6.62682281e-310, 4.65671518e-310, 0.00000000e+000],
       [0.00000000e+000, 6.62678066e-310, 1.50008929e+248],
       [4.31174539e-096, 9.80058441e+252, 1.23971686e+224],
       [2.59033217e-144, 6.06003395e+233, 1.06400250e+248],
       [2.59050167e-144, 5.22286946e-143, 6.32404027e-322]])

In [ ]:
# Mission 5 : Create an array filled with only zeros. You can choose the length of this array.
np.zeros((6, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
# Mission 6 : Create an array filled with 10 random integers.
np.random.randint(1000, size=(1, 2, 5))
# yep there a 3 dims

array([[[499, 176, 599, 356, 129],
        [193, 343,  96, 867, 984]]])

In [ ]:
# Mission 7 : Create an array that contains 50 values randomly selected only from these numbers: 0, 1, 2, 3, 4, 5, 6, 7.
np.random.randint(0, 8, size=50)


array([1, 5, 2, 3, 3, 6, 1, 0, 7, 4, 0, 0, 2, 4, 2, 4, 1, 0, 1, 1, 3, 7,
       4, 5, 6, 7, 3, 4, 6, 7, 2, 1, 5, 2, 7, 3, 3, 2, 0, 2, 4, 6, 0, 7,
       0, 3, 4, 1, 4, 6])